AWSTemplateFormatVersion: '2010-09-09'
Description: Application VPC with public, private, and data subnets

Resources:
  ApplicationVPC:
   Type: AWS::EC2::VPC
   Properties:
    CidrBlock: '192.168.0.0/16'
    EnableDnsSupport: true
    EnableDnsHostnames: true
    Tags:
      - Key: Name
        Value: ApplicationVPC

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: 
        Ref: ApplicationVPC
      Tags:
        - Key: Name
          Value: PublicRouteTable

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: 
        Ref: ApplicationVPC
      Tags:
        - Key: Name
          Value: PrivateRouteTable

  PubSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: ApplicationVPC
      CidrBlock: 192.168.1.0/24
      AvailabilityZone: "us-west-2a"
      Tags:
      - Key: stack
        Value: public subnet1

  PubSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: ApplicationVPC
      CidrBlock: 192.168.2.0/24
      AvailabilityZone: "us-west-2b"
      Tags:
      - Key: stack
        Value: public subnet2

  PvtSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: 
        Ref: ApplicationVPC
      CidrBlock: 192.168.3.0/24
      AvailabilityZone: "us-west-2a"
      Tags:
      - Key: stack
        Value: private subnet1

  PvtSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
       Ref: ApplicationVPC
      CidrBlock: 192.168.4.0/24
      AvailabilityZone: "us-west-2b"
      Tags:
      - Key: stack
        Value: private subnet2

  DataSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: 
        Ref: ApplicationVPC
      CidrBlock: 192.168.5.0/24
      AvailabilityZone: "us-west-2a"
      Tags:
      - Key: stack
        Value: private subnet1

  DataSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
       Ref: ApplicationVPC
      CidrBlock: 192.168.6.0/24
      AvailabilityZone: "us-west-2b"
      Tags:
      - Key: stack
        Value: private subnet2

  NATGateway1EIP:
     Type: AWS::EC2::EIP
     Properties:
       Domain: vpc

  NATGateway2EIP:
     Type: AWS::EC2::EIP
     Properties:
       Domain: vpc

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: InternetGateway_APP

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: 
        Ref: ApplicationVPC
      InternetGatewayId:  
        Ref: InternetGateway