AWSTemplateFormatVersion: '2010-09-09'
Description: Application VPC with public, private, and data subnets

Resources:
  ApplicationVPC:
   Type: AWS::EC2::VPC
   Properties:
    CidrBlock: '192.168.0.0/16'
    EnableDnsSupport: true
    EnableDnsHostnames: true
    Tags:
      - Key: Name
        Value: ApplicationVPC

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: 
        Ref: ApplicationVPC
      CidrBlock: '192.168.1.0/24'
      AvailabilityZone: 'us-west-2a'
      Tags:
        - Key: Name
          Value: PublicSubnet

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: 
        Ref: ApplicationVPC
      CidrBlock: '192.168.2.0/24'
      AvailabilityZone: 'us-west-2b'
      Tags:
        - Key: Name
          Value: PublicSubnet