AWSTemplateFormatVersion: '2010-09-09'
Description: Application VPC with public, private, and data subnets

Resources:
 ApplicationVPC:
  Type: AWS::EC2::VPC
  Properties:
    CidrBlock: '10.0.0.0/16'
    EnableDnsSupport: true
    EnableDnsHostnames: true
    Tags:
      - Key: Name
        Value: ApplicationVPC

