AWSTemplateFormatVersion: '2010-09-09'
Description: Management VPC with public and private subnets

Resources:
  ManagementVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: '10.0.0.0/16'
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: ManagementVPC

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: 
        Ref: ManagementVPC
      CidrBlock: '10.0.0.0/24'
      AvailabilityZone: 'us-west-2a'
      Tags:
        - Key: Name
          Value: PublicSubnet

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: 
        Ref: ManagementVPC
      CidrBlock: '10.0.1.0/24'
      AvailabilityZone: 'us-west-2b'
      Tags:
        - Key: Name
          Value: PrivateSubnet
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: InternetGateway