AWSTemplateFormatVersion: '2010-09-09'
Description: Management VPC with public and private subnets

Resources:
  ManagementVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: '10.0.0.0/16'
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: ManagementVPC